"""
report_agent.py
────────────────────────────────────────────
Unified Operational Reporting Agent for AOIP.

Combines:
    • KPI metrics from InsightAgent
    • RCA spotlight from RCAAgent
    • HTML report generation
    • Native PDF export using ReportLab
"""

# ───────── IMPORTS ─────────
from datetime import datetime
from pathlib import Path
from jinja2 import Template

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

from insight_agent import InsightAgent
from rca_agent import RCAAgent


# ───────── CONFIG ─────────
BASE_DIR = Path(__file__).resolve().parent
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


# ───────── HTML TEMPLATE ─────────
REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{{ title }}</title>
<style>
 body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
 h1,h2 { color: #004e92; }
 .kpi-box {
     margin: 12px 0;
     padding: 10px;
     border-left: 4px solid #004e92;
     background: #f5f5f5;
 }
 .section { margin-bottom: 25px; }
</style>
</head>
<body>

<h1>{{ title }}</h1>
<p><b>Date Generated:</b> {{ date_created }}</p>

<div class="section">
<h2>KPI Summary</h2>
{% for k, v in kpis.items() %}
<div class="kpi-box"><b>{{ k }}</b>: {{ v }}</div>
{% endfor %}
</div>

<div class="section">
<h2>Root Cause Spotlight</h2>
<ul>
<li><b>Ticket:</b> {{ rca['Ticket_ID'] }}</li>
<li><b>Category:</b> {{ rca['Category'] }}</li>
<li><b>Issue:</b> {{ rca['Root_Cause'] }}</li>
<li><b>Mitigation:</b> {{ rca['Mitigation'] }}</li>
<li><b>Severity:</b> {{ rca['Severity'] }}</li>
<li><b>Last Occurrence:</b> {{ rca['Last_Occurrence'] }}</li>
</ul>
</div>

<div class="section">
<h2>Executive Summary</h2>
<p>
SLA performance remains healthy with breach rate of
<b>{{ kpis['Breach_Rate(%)'] }}%</b>,
average resolution time of
<b>{{ kpis['Avg_Resolution_Hrs'] }} hrs</b>,
and CSAT of
<b>{{ kpis['Avg_CSAT'] }}</b>.
Focused attention is recommended on
<b>{{ rca['Category'] }}</b> issues caused by
<b>{{ rca['Root_Cause'] }}</b>.
Mitigation action:
<b>{{ rca['Mitigation'] }}</b>.
</p>
</div>

<footer style="margin-top:20px;color:#666;">
Generated by AOIP ReportAgent
</footer>

</body>
</html>
"""


# ───────── REPORT AGENT ─────────
class ReportAgent:
    """
    Combines KPI + RCA into stakeholder-ready reports.
    """

    def __init__(self, insight_agent=None, rca_agent=None):
        self.insight_agent = insight_agent or InsightAgent()
        self.rca_agent = rca_agent or RCAAgent()

    # ───── HTML BUILD ─────
    def build_html(self, ticket_id: str) -> str:
        kpis = self.insight_agent.summary_report()
        rca = self.rca_agent.get_root_cause(ticket_id)

        return Template(REPORT_TEMPLATE).render(
            title="AOIP Operational Intelligence Report",
            kpis=kpis,
            rca=rca,
            date_created=datetime.now().strftime("%Y-%m-%d %H:%M"),
        )

    # ───── SAVE HTML ─────
    def save_html(self, ticket_id: str) -> Path:
        html = self.build_html(ticket_id)

        out_path = REPORTS_DIR / f"Report_{ticket_id}.html"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"✅ HTML report saved → {out_path}")
        return out_path

    # ───── PDF EXPORT ─────
    def export_pdf(self, ticket_id: str) -> Path:
        pdf_path = REPORTS_DIR / f"Report_{ticket_id}.pdf"

        kpis = self.insight_agent.summary_report()
        rca = self.rca_agent.get_root_cause(ticket_id)

        styles = getSampleStyleSheet()
        normal = styles["Normal"]
        title = styles["Title"]
        heading = styles["Heading2"]

        story = []

        story.append(Paragraph("AOIP Operational Intelligence Report", title))
        story.append(Spacer(1, 0.2 * inch))
        story.append(
            Paragraph(
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                normal
            )
        )

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("KPI Summary", heading))

        for k, v in kpis.items():
            story.append(Paragraph(f"<b>{k}</b>: {v}", normal))

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Root Cause Spotlight", heading))

        for k, v in rca.items():
            story.append(Paragraph(f"<b>{k}</b>: {v}", normal))

        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Executive Summary", heading))
        story.append(
            Paragraph(
                f"""
                SLA breach rate is <b>{kpis['Breach_Rate(%)']}%</b>,
                average resolution is <b>{kpis['Avg_Resolution_Hrs']} hrs</b>,
                and CSAT is <b>{kpis['Avg_CSAT']}</b>.
                Primary concern remains <b>{rca.get('Category', '')}</b>
                caused by <b>{rca.get('Root_Cause', '')}</b>.
                Recommended mitigation: {rca.get('Mitigation', '')}.
                """,
                normal
            )
        )

        doc = SimpleDocTemplate(str(pdf_path))
        doc.build(story)

        print(f"📄 PDF report created → {pdf_path}")
        return pdf_path


# ───────── TEST RUN ─────────
if __name__ == "__main__":
    print("🚀 Generating AOIP operational report...")

    report_agent = ReportAgent()

    sample_ticket = "TCK00025"

    report_agent.save_html(sample_ticket)
    report_agent.export_pdf(sample_ticket)